### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by jgroom33** [cyaninc/rsign#2]
Here's a JavaScript implementation

``` javascript
mdso_getHash = function (method, path) {
  import { Random } from 'meteor/random'
  var appSettings = AppSettings.findOne();
  var port = 443;
  var api_key_id = appSettings.MDSO_keyID;
  var api_secret = appSettings.MDSO_keySecret;
  var nonce = Random.secret().valueOf();

  var timestamp = new Date().valueOf();

  var host = appSettings.MDSO_server.substring(appSettings.MDSO_server.indexOf('//') + 2 ,50)
  var string_to_sign = [timestamp, nonce, method, path, host, port].join("\n")
  var hash = CryptoJS.HmacSHA256(string_to_sign, api_secret).toString(CryptoJS.enc.hex);
  var base64 = new Buffer(hash, 'hex').toString("base64");

  var header = "MAC id=\"" + api_key_id + "\", ts=\"" + timestamp + "\", nonce=\"" + nonce + "\", mac=\"" + base64 + "\"";
  return header;
};
```

**Comment by Xpress01** [comment]
Fixed a few problems with semicolons and the import should be at the beginning. 

import { Random } from 'meteor/random';

mdso_getHash = function (method, path) {
  var appSettings = AppSettings.findOne();
  var port = 443;
  var api_key_id = appSettings.MDSO_keyID;
  var api_secret = appSettings.MDSO_keySecret;
  var nonce = Random.secret().valueOf();

  var timestamp = new Date().valueOf();

  var host = appSettings.MDSO_server.substring(appSettings.MDSO_server.indexOf('//') + 2 ,50);
  var string_to_sign = [timestamp, nonce, method, path, host, port].join("\n");
  var hash = CryptoJS.HmacSHA256(string_to_sign, api_secret).toString(CryptoJS.enc.hex);
  var base64 = new Buffer(hash, 'hex').toString("base64");

  var header = "MAC id=\"" + api_key_id + "\", ts=\"" + timestamp + "\", nonce=\"" + nonce + "\", mac=\"" + base64 + "\"";
  return header;
};
